In [5]:
import sklearn.linear_model

In [7]:
from sklearn.linear_model import LassoCV

In [ ]:
# regression)model ridge, lasso, elastic_net 을 키로 하여 구현되는 모델


In [ ]:

#Set the different values of alpha to be tested
#alpha_ridge = [1e-15, 1e-10, 1e-8, 1e-4, 1e-3,1e-2, 1, 5, 10, 20]

In [ ]:
#각각은 alpha , l1_ratio , pred, cofficients

In [10]:
import pandas as pd

In [11]:
data_train = pd.read_csv('./data/data_train.csv')

In [12]:
data_test = pd.read_csv('./data/data_test.csv')

In [16]:
lasso_cv = LassoCV(alphas=)

In [ ]:
from sklearn.linear_model import RidgeCV


In [36]:
data_train['price']

0      410.0
1      100.0
2       50.0
3       80.0
4      400.0
       ...  
329    290.0
330    220.0
331     80.0
332     50.0
333    120.0
Name: price, Length: 334, dtype: float64

In [ ]:
def regression(data_train, data_test):


    return {'ridge' : , 'lasso', 'elastic_net'}

In [ ]:
# 등위 접속사 해석을 못해서 제대로 해석을 못하는건가


In [99]:
def elastic_regression(data, alpha):
    # Fit the model
    x = data.iloc[:,:-1].values
    y = data['price'].values
    elasticreg = ElasticNetCV(normalize=True,alphas=alpha,l1_ratio=np.arange(0.6,1,0.1))
    elasticreg.fit(x,y)
    # y_pred = ridgereg.predict(x)
    return elasticreg

In [106]:
def ridge_regression(data,  alpha ):
    # Fit the model
    x = data.iloc[:,:-1].values
    y = data['price'].values
    ridgereg = RidgeCV(normalize=True,alphas=alpha)
    ridgereg.fit(x,y)
    # y_pred = ridgereg.predict(x)

    return ridgereg

In [107]:
def lasso_regression(data,  alpha ):
    # Fit the model
    x = data.iloc[:,:-1].values
    y = data['price'].values
    lassoreg = LassoCV(normalize=True,alphas=alpha)
    lassoreg.fit(x,y)
    # y_pred = ridgereg.predict(x)
    return lassoreg

In [102]:
import numpy as np

In [103]:
alpha_ridge = np.logspace(-4,-1,4)

In [104]:
elasticreg = elastic_regression(data_train,alpha=alpha_ridge)

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:633: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 198315.15686030837, tolerance: 675.1469850187265
  model = cd_fast.enet_coordinate_descent_gram(
c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:633: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 105453.80449045866, tolerance: 675.1469850187265
  model = cd_fast.enet_coordinate_descent_gram(
c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:633: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 186254.02668569091, tolerance: 715.8360299625468
  model = cd_fast.enet_coordinate_descent_gram(
c:\user

In [127]:
elasticreg.l1_ratio_

0.7999999999999999

In [123]:
# coef 가 0.001 이상인 값으로 획득하기
abs(ridgereg.coef_) > 0.001

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True, False, False])

In [122]:
lassoreg.coef_ != 0

array([False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True, False, False, False,  True, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False,  True,  True, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False,  True, False,  True, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True,  True, False, False, False, False,  True,  True,
       False,  True, False, False, False, False, False, False,  True,
       False, False,  True, False, False,  True, False, False, False,
        True,  True,  True, False, False,  True, False, False])

In [124]:
abs(elasticreg.coef_) > 0.001

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True, False, False, False,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True, False, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True, False,  True,  True, False, False, False, False,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True, False, False])

In [115]:
elasticreg.alpha_

0.0001

In [ ]:
elasticreg.predict(data_test.iloc[:,:-1])

In [108]:
lassoreg = lasso_regression(data_train,alpha = alpha_ridge)

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:633: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1616.469873095397, tolerance: 675.1469850187265
  model = cd_fast.enet_coordinate_descent_gram(
c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:633: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 35242.89355912154, tolerance: 675.1469850187265
  model = cd_fast.enet_coordinate_descent_gram(
c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:633: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 57584.45969396205, tolerance: 675.1469850187265
  model = cd_fast.enet_coordinate_descent_gram(
c:\users\d

In [117]:
lassoreg.alpha_

0.01

In [109]:
lassoreg.predict(data_test.iloc[:,:-1])

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LassoCV was fitted without feature names
  warnings.warn(


array([  6.221456  , 531.2477246 , 377.34692385, 134.60559544,
       154.2094413 , 102.41442172, 362.96832198, 263.10240957,
       334.38451313, 167.28959366])

In [72]:
from sklearn.linear_model import ElasticNetCV

In [112]:
def ridge_regression(data,  alpha ):
    # Fit the model
    x = data.iloc[:,:-1].values
    y = data['price'].values
    ridgereg = RidgeCV(normalize=True,alphas=alpha)
    ridgereg.fit(x,y)
    # y_pred = ridgereg.predict(x)

    return ridgereg

In [113]:
ridgereg = ridge_regression(data_train,alpha=alpha_ridge)

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), _RidgeGCV())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


In [114]:
ridgereg.predict(data_test.iloc[:,:-1])

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RidgeCV was fitted without feature names
  warnings.warn(


array([  1.27222324, 536.34987359, 384.69842927, 131.76890028,
       166.2896877 , 104.64339239, 350.55107093, 262.11499878,
       338.08007058, 169.28671441])

In [74]:
elasticreg = elastic_regression(data_train,alpha=alpha_ridge)

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), ElasticNet())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to original_alpha * np.sqrt(n_samples) if l1_ratio is 1, and to original_alpha * n_samples if l1_ratio is 0. For other values of l1_ratio, no analytic formula is available.
  warnings.warn(


In [118]:
elasticreg.alpha_

0.0001

In [75]:
elasticreg.predict(data_test.iloc[:,:-1])

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but ElasticNetCV was fitted without feature names
  warnings.warn(


array([ 66.29125608, 365.64890598, 325.90450627, 216.66741267,
       149.64502922, 145.7556738 , 317.45152104, 226.45545466,
       395.70382563, 176.98036106])

In [ ]:
ElasticNetCV(normalize=True)

In [71]:
lassoreg.predict(data_test.iloc[:,:-1])

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LassoCV was fitted without feature names
  warnings.warn(


array([ 14.73166115, 516.87584599, 373.68631222, 143.31667929,
       148.05117858, 107.00180673, 371.41469042, 251.7472754 ,
       330.5699473 , 168.58368161])

In [63]:
ridgereg = ridge_regression(data_train,alpha=alpha_ridge)

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), _RidgeGCV())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


In [65]:
# 조금 비슷한데 ridge
# test 값과 그래도 많이 비슷하게 나오긴 했다 이렇게하면되는거엿나
ridgereg.predict(data_test.iloc[:,:-1])

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RidgeCV was fitted without feature names
  warnings.warn(


array([  5.80772084, 472.81535392, 381.16598691, 160.51305898,
       197.5619631 , 115.12161272, 367.46426979, 245.96148448,
       353.50640771, 166.91465556])

array([ 410.,  100.,   50.,   80.,  400.,  160.,   60.,  130.,  450.,
        700.,  700.,  490.,  240.,  430.,  310.,  120.,   70.,  290.,
        370.,   30.,  270.,  410.,  470.,   20.,  340.,  270.,  230.,
        340.,   70.,  200.,   90.,  150.,  400.,   70.,  190.,  140.,
         40.,   50.,   70.,   80.,  220.,  590.,  290.,  270.,  600.,
        240.,  110.,  400.,  110.,   50.,   60.,   30.,  220.,  450.,
        420.,   40.,  140.,  500.,   70.,  630.,  170.,  370.,  170.,
        160.,  170.,  280.,  180.,  300.,  220.,  150.,   50.,  100.,
        300.,  250.,  140.,  450.,  240.,  260.,  300.,  650.,  100.,
        170.,   20.,  140.,   60.,  145.,  230.,  100.,   90.,  100.,
        390.,  200.,  330.,  180.,  130.,  150.,  110.,  900.,  150.,
        190.,  150.,  310.,  120.,  370.,  210.,  360.,   30.,  270.,
        160.,  260.,  100.,  180.,  200.,   90.,   30.,  370.,  140.,
        130.,  390.,   90.,   90.,  380.,  170.,  300.,   90.,  400.,
         90.,  100.,

In [ ]:
label = data_train

In [28]:
lasso_cv.fit(data_train.iloc[:,:-1].values, y =data_train['price'].values)

c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:633: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 681.2812369135208, tolerance: 675.1469850187265
  model = cd_fast.enet_coordinate_descent_gram(
c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:633: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 881.6959083313122, tolerance: 675.1469850187265
  model = cd_fast.enet_coordinate_descent_gram(
c:\users\data\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:633: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3566.8699054764584, tolerance: 715.8360299625468
  model = cd_fast.enet_coordinate_descent_gram(
c:\users\

LassoCV()

In [33]:
lasso_cv.predict(data_test.iloc[:,:-1].values)

array([108.13701704, 314.45676954, 256.61381562, 211.10609393,
       114.04922629, 164.63046843, 259.43077865, 178.03032145,
       469.31937275, 156.83631433])

array([[8.30000000e+02, 2.60000000e+02, 2.49000000e+01, 3.00000000e+01,
        2.16220000e+02, 4.00000000e+00, 1.90000000e+02, 1.58000000e+03,
        4.03000000e+01, 4.08400000e+01, 1.15000000e+00, 1.50266800e+05,
        1.14950000e+03, 3.41000000e+01, 2.14350000e+02, 4.86683000e+03,
        5.73726531e+02, 6.80290000e+02, 1.75500000e+03, 6.71400000e+03,
        4.34000000e+01, 3.64500000e+01, 1.53516000e+03, 2.92995000e+04,
        4.66212200e+05, 2.62800000e+03, 3.93000000e+01, 4.02100000e+01,
        1.52000000e+00, 1.43737700e+05, 1.28450000e+03, 3.35000000e+01,
        1.42900000e+02, 3.24455000e+03, 1.50000000e+01, 5.54081966e+02,
        6.63970000e+02, 1.75500000e+03, 5.82700000e+03, 4.17900000e+01,
        3.47600000e+01, 1.52755000e+03, 1.95330000e+04, 4.09677900e+05,
        2.37400000e+03, 3.80000000e+01, 3.94300000e+01, 9.20000000e-01,
        1.34548400e+05, 1.19110000e+03, 3.37000000e+01, 7.14500000e+01,
        1.62228000e+03, 5.74600000e+02, 6.80500000e+02, 1.755000

In [13]:
data_train

S_0    S_1    S_2    S_3     S_4   S_5     S_6     S_7    S_8     S_9  \
0    1450.0  320.0  377.0  260.0  443.35   7.0  3100.0  5909.0  177.6  147.44   
1     360.0   80.0   21.6   60.0  644.47  11.0   330.0  3302.0   29.5   29.93   
2     920.0  290.0   36.8   40.0  325.39   4.0   370.0  4638.0   34.6   37.16   
3    1670.0  370.0   83.5   50.0  291.99   7.0   410.0  6788.0   54.2   59.40   
4    2600.0  560.0  598.0  230.0  415.24  10.0  2100.0  5606.0  149.1  134.80   
..      ...    ...    ...    ...     ...   ...     ...     ...    ...     ...   
329  3240.0  630.0  680.4  210.0  715.52   7.0  2300.0  3157.0   92.8   96.49   
330   390.0  100.0   62.4  160.0  547.10   8.0  1000.0  3678.0   86.2   83.21   
331   750.0  200.0   45.0   60.0  423.07   6.0   360.0  3213.0   44.5   49.80   
332   560.0  220.0   22.4   40.0  319.47   3.0   350.0  2374.0   38.0   39.43   
333  1430.0  440.0   57.2   40.0  772.31   4.0   280.0  3321.0   31.4   33.00   

     ...         S_89     S_90     S_91    S_92    S_93    S_94     S_95  \
0    ...  1994.600000  2025.00  9185.48  9208.0  123.37  127.33  9501.30   
1    ...   284.100000   346.10  1750.00  3739.0   24.05   16.21  1013.40   
2    ...   431.100000   550.40  1755.00  4252.0   30.13   21.54  2134.49   
3    ...   769.600000   717.90  1755.00  8231.0   56.99   48.40  2556.96   
4    ...  1821.600000  1963.70  9114.22  9131.0  116.56  119.13  9459.40   
..   ...          ...      ...      ...     ...     ...     ...      ...   
329  ...  1014.900000  1104.70  8148.33  8186.0   83.55   80.05  6703.06   
330  ...  1005.000000  1270.50  8002.21  8058.0   79.65   76.92  5062.76   
331  ...   554.081966   663.97  1755.00  5827.0   41.79   34.76  1527.55   
332  ...   229.200000   582.90  1755.00  4758.0   34.98   27.13  1859.50   
333  ...   225.700000   409.30  1750.00  4063.0   27.84   18.37  1549.44   

         S_96       S_97  price  
0    24130.00  1660444.0  410.0  
1    17881.50   428725.0  100.0  
2    18409.00   402158.1   50.0  
3    20703.50   605688.7   80.0  
4    47096.00  1391757.1  400.0  
..        ...        ...    ...  
329  11208.75   817526.9  290.0  
330  43710.00   788018.3  220.0  
331  19533.00   409677.9   80.0  
332   9483.25   408321.5   50.0  
333  35763.00   420700.5  120.0  

[334 rows x 99 columns]